spring:
  datasource:
    url: jdbc:postgresql://localhost:5332/urlshortener
    username: amanbansal
    password: password
    driverClassName: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
      show-sql: true